breadscanso/urls.py
from django.urls import path, include
from main import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from main.views import google_login, naver_login

from django.conf import settings
from django.conf.urls.static import static


# namespace 지정
app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('summernote/', include('django_summernote.urls')),  # summernote 텍스트 에디터 추가
    path('main/', include('main.urls')), # 회원 관련 URL
    path('kiosk/', include('kiosk.urls')),  # kiosk 앱의 urls.py를 포함
    path('brand/', include('brand.urls')),  # brand 앱의 urls.py를 포함
    path('event/', include('event.urls')),  # event 앱의 urls.py를 포함
    path('member/', include('member.urls')),  # member 앱의 urls.py를 포함
    path('menu/', include('menu.urls')),  # menu 앱의 urls.py를 포함
    path('notice/', include('notice.urls')),  # notice 앱의 urls.py를 포함
    path('pay/', include('pay.urls')),  # pay 앱의 urls.py를 포함
    path('qna/', include('qna.urls')),  # qna 앱의 urls.py를 포함
    path('sales/', include('sales.urls')),  # sales 앱의 urls.py를 포함
    path('stock/', include('stock.urls')),  # stock 앱의 urls.py를 포함
    path('store/', include('store.urls')),  # store 앱의 urls.py를 포함
    path('store_info/', include('store_info.urls')),  # store_info 앱의 urls.py를 포함
    path('admin/', admin.site.urls),  # 소셜로그인 추가
    path('accounts/', include('allauth.urls')),  # 소셜로그인 추가, allauth 관련 url 추가
    path('google-login/', google_login, name='google_login'),
    path('naver-login/', naver_login, name='naver_login'),
]

# 개발 환경에서 미디어 파일 서빙
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# from django.urls import path, include
# from main import views
# from django.contrib.auth import views as auth_views
#
# # namespace 지정
# app_name = 'main'
#
# urlpatterns = [
#     path('', views.index, name='index'),
#     path('kiosk/', include('kiosk.urls')),  # kiosk 앱의 urls.py를 포함
#     path('brand/', include('brand.urls')),  # brand 앱의 urls.py를 포함
#     path('event/', include('event.urls')),  # event 앱의 urls.py를 포함
#     path('member/', include('member.urls')),  # member 앱의 urls.py를 포함
#     path('menu/', include('menu.urls')),  # menu 앱의 urls.py를 포함
#     path('notice/', include('notice.urls')),  # notice 앱의 urls.py를 포함
#     path('pay/', include('pay.urls')),  # pay 앱의 urls.py를 포함
#     path('qna/', include('qna.urls')),  # qna 앱의 urls.py를 포함
#     path('sales/', include('sales.urls')),  # sales 앱의 urls.py를 포함
#     path('stock/', include('stock.urls')),  # stock 앱의 urls.py를 포함
#     path('store/', include('store.urls')),  # store 앱의 urls.py를 포함
#     path('store_info/', include('store_info.urls')),  # store_info 앱의 urls.py를 포함
#     path("login/", auth_views.LoginView.as_view(template_name="main/login.html"), name="login"),  # 로그인 경로
#     path("logout/", auth_views.LogoutView.as_view(next_page="/"), name="logout"),  # 로그아웃 경로
#     path("signup/", views.signup, name="signup"),  # 회원가입 경로
#     path("login_find/", views.login_find, name="login_find"), # ID/PW 찾기 경로
# ]

main/urls.py
from django.urls import path, include
from main import views
from django.contrib.auth import views as auth_views

# namespace 지정
app_name = 'main'

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.user_login, name="login"),
    # path("login/", auth_views.LoginView.as_view(template_name="main/login.html"), name="login"),  # 로그인 경로
    # path("logout/", auth_views.LogoutView.as_view(next_page="/"), name="logout"),  # 로그아웃 경로
    path("logout/", views.user_logout, name="logout"),
    path("signup/", views.signup, name="signup"),  # 회원가입 경로
    path("login_find/", views.login_find, name="login_find"),  # ID/PW 찾기 경로
    path("check_user_id/", views.check_user_id, name="check_user_id"), # AJAX 요청 받는 아이디 중복 확인용
    path("sales/", include("sales.urls")), # sales 앱 URL 포함하기
    path("store_signup/", views.store_signup, name="store_signup"),  # 매장페이지-회원가입 경로
]

member/urls.py
from django.urls import path
from . import views  # views.py에서 함수 가져오기
from .views import check_user_id

app_name = 'member'

urlpatterns = [
    path('', views.member_main, name='member_main'),  # /member/
    path('member_page/', views.member_page, name='member_page'), # 회원 마이페이지
    path('member_edit/', views.member_edit, name='member_edit'), # 회원정보수정 페이지
    path('check-user-id/', views.check_user_id, name='check_user_id'), # 회원정보수정 - 아이디중복확인
    path('member_pw/', views.member_pw, name='member_pw'), # 비밀번호변경 페이지
    path("check_password/", views.check_password, name="check_password"),  # 비밀번호 확인
    path('member_delete/', views.member_delete, name='member_delete'), # 회원탈퇴 페이지
    path('member_delete_detail/', views.member_delete_detail, name='member_delete_detail'), # 회원탈퇴 detail 페이지
    path('mypoint/', views.mypoint, name='mypoint'), # 포인트 적립 페이지
]












# from django.urls import path
# from . import views  # views.py에서 함수 가져오기
#
#
# urlpatterns = [
#     path('', views.member_main, name='member_main'),  # /member/
#     path('store/', views.member_store, name='member_store'), # 점주 회원관리
#     path('member_page/', views.member_page, name='member_page'), # 회원 마이페이지
#     path('member_edit/', views.member_edit, name='member_edit'), # 회원정보수정 페이지
#     path('member_pw/', views.member_pw, name='member_pw'), # 비밀번호변경 페이지
#     path('member_delete/', views.member_delete, name='member_delete'), # 회원탈퇴 페이지
#     path('member_delete_detail/', views.member_delete_detail, name='member_delete_detail'), # 회원탈퇴 사유입력 페이지
# ]

pay/urls.py
from django.urls import path
from . import views  # views.py에서 함수 가져오기

# namespace 지정
app_name = 'pay'

urlpatterns = [
    path('', views.pay_main, name='pay_main'),  # /pay/

    path('details/<int:payment_id>/', views.pay_details, name='pay_details'),

    path('cancel/', views.pay_cancel, name='pay_cancel'),

    path('member/', views.pay_member, name='pay_member'),

    path('member/cancel/', views.pay_member_cancel, name='pay_member_cancel'),

    path('member/details/<int:payment_id>/', views.pay_member_details, name='pay_member_details'),
    # path('member/details/<int:payment_id>/', views.pay_member_details, name='pay_member_details'),

]

store/urls.py
from django.urls import path
from . import views  # views.py에서 함수 가져오기
from django.conf.urls.static import static
from django.conf import settings


app_name = 'store'

urlpatterns = [
    path('', views.store_main, name='store_main'),  # /store/
    path('member_store/', views.member_store, name='member_store'), # 매장페이지 - 회원관리
    path('update_member_store/', views.update_member_store, name='update_member_store'), # 매장페이지 - 회원관리 내 수정
    path('delete_member_store/', views.delete_member_store, name='delete_member_store'),  # 회원 삭제
    path('store_home_edit/', views.store_home_edit, name='store_home_edit'),  # 첫 번째 화면
    path('store_home_edit_details/', views.store_home_edit_details, name='store_home_edit_details'),  # 두 번째 화면
    path('about_breadscanso_edit', views.about_breadscanso_edit, name='about_breadscanso_edit'),  # 브랜드 소개
    path('store_map/', views.store_map, name='store_map'),  # 매장 안내
    path('store_map', views.store_map, name='store_map'),  # 매장 안내
    path('store_map/edit', views.store_map_edit, name='store_map_edit'),  # 매장 안내 수정
    path('store_event', views.store_event, name='store_event'),  # 이벤트 목록
    path('store_event/add', views.store_event_add, name='store_event_add'),  # 이벤트 신규등록 페이지
    path('event/<int:event_id>/edit/', views.event_edit, name='store_event_edit'),  # 수정 페이지 URL
    path('delete_store_event/', views.delete_store_event, name='delete_store_event'),  # 이벤트 삭제

    # path('community_notice', views.community_notice, name='community_notice'),  # 커뮤니티/공지사항
    # path('community_notice/write', views.community_notice_write, name='community_notice_write'),  # 커뮤니티/공지사항 글쓰기
    # path('community_notice/modify/<int:notice_id>', views.community_notice_modify, name='community_notice_modify'),  # 커뮤니티/공지사항 수정
    # path('community_qna', views.community_qna, name='community_qna'),  # 커뮤니티/Q&A

    # # question관련 view
    # path('community_qna/question/<int:qna_id>/', views.question_detail, name='question_detail'),
    # path('community_qna/question/create/', views.question_create, name='question_create'),
    # path('community_qna/question/modify/<int:qna_id>/', views.question_modify, name='question_modify'),
    # path('community_qna/question/delete/<int:qna_id>/', views.question_delete, name='question_delete'),
    #
    # # question관련 view - ajax
    # # path('community_qna/question/search/', views.question_search, name='question_search'),
    # # path('community_qna/question/vote/<int:question_id>/', views.question_vote, name='question_vote'),
    #
    # # answer관련 view
    # path('community_qna/answer/create/<int:qna_id>/',views.answer_create, name='answer_create'),
    # path('community_qna/answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    # path('community_qna/answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    #
    # # answer관련 view - ajax
    # # path('community_qna/answer/vote/<int:answer_id>/', views.answer_vote, name='answer_vote'),


    path('store_account', views.store_account, name='store_account'),  # 매장정보
]


# 개발 환경에서 미디어 파일 처리
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/member/member_delete.html
{% extends 'layout/member/member_base.html' %}
{% load static %}

{% block title %}회원탈퇴{% endblock title %}

{% block header %}
    {% include 'layout/member/member_header.html' %}
{% endblock header %}

{% block sidebar %}
    {% include 'layout/member/member_sidebar.html' %}
{% endblock sidebar %}

{% block content %}
    <h3 style="margin-bottom: 50px;" class="text-center">회원탈퇴</h3>

    <form class="row g-3">
        <div class="col-auto">
            <input type="text" readonly class="form-control-plaintext" id="staticEmail2" value="비밀번호">
        </div>
        <div class="col-auto">
            <input type="password" class="form-control" id="inputPassword2" placeholder="비밀번호를 입력해주세요">
        </div>
        <div class="col-auto">
            <button type="button" id="confirmButton" class="btn btn-primary" onclick="location.href='{% url 'member:member_delete_detail' %}'">확인</button>
        </div>
    </form>
{% endblock content %}

templates/member/member_edit.html
{% extends 'layout/member/member_base.html' %}
{% load static %}

{% block title %}회원정보수정{% endblock title %}

{% block header %}
    {% include 'layout/member/member_header.html' %}
{% endblock header %}

{% block sidebar %}
    {% include 'layout/member/member_sidebar.html' %}
{% endblock sidebar %}

{% block content %}
    <h3 style="margin-bottom: 50px;" class="text-center">회원정보수정</h3>
    <div class="container">
        <form id="memberEditForm" method="POST" action="{% url 'member:member_edit' %}" enctype="multipart/form-data">
            {% csrf_token %}

            <!-- 아이디 -->
            <div class="mb-3">
                <label for="user_id">* 아이디</label>
                <div class="input-group">
                    <input type="text" name="user_id" id="user_id" class="form-control" value="{{ member.member_id }}" required>
                    <button type="button" id="check-username-btn" class="btn btn-secondary" onclick="checkUsername()">중복 확인</button>
                </div>
                <small id="username-check-result" class="form-text"></small>
            </div>


            <!-- 이름 -->
            <div class="mb-3">
                <label for="name" class="w-100 text-start">* 이름</label>
                <input type="text" id="name" name="name" class="form-control"
                       value="{% if member %}{{ member.name }}{% endif %}">
            </div>

            <!-- 휴대폰 번호 -->
            <div class="mb-3">
                <label for="phone_num" class="w-100 text-start">* 휴대폰 번호</label>
                <input type="number" id="phone_num" name="phone_num" class="form-control"
                       value="{% if member %}{{ member.phone_num }}{% endif %}">
            </div>

            <!-- 프로필 이미지 -->
            <div class="mb-3">
                <label for="profile_image" class="form-label w-100 text-start">프로필</label>
                {% if member.profile_image %}
                    <img src="{{ member.profile_image.url }}" alt="Current Profile" class="mb-2" style="max-width: 200px;">
                {% endif %}
                <input class="form-control" type="file" id="profile_image" name="profile_image">
            </div>

            <!-- 이메일 입력 폼 수정 -->
            <div class="mb-3">
                <label for="email_id">* 이메일</label>
                <div class="d-flex">
                    <input type="text" id="email_id" class="form-control" value="{{ email_parts.id }}">
                    <span class="mx-2">@</span>
                    <select id="email_domain" class="form-control">
                        <option value="naver.com" {% if email_parts.domain == 'naver.com' %}selected{% endif %}>naver.com</option>
                        <option value="gmail.com" {% if email_parts.domain == 'gmail.com' %}selected{% endif %}>gmail.com</option>
                        <option value="daum.net" {% if email_parts.domain == 'daum.net' %}selected{% endif %}>daum.net</option>
                        <option value="직접입력" {% if email_parts.domain and email_parts.domain not in 'naver.com,gmail.com,daum.net' %}selected{% endif %}>직접입력</option>
                    </select>
                    <input type="text" id="email_custom" class="form-control {% if not email_parts.domain or email_parts.domain in 'naver.com,gmail.com,daum.net' %}d-none{% endif %}"
                        placeholder="직접입력" value="{% if email_parts.domain and email_parts.domain not in 'naver.com,gmail.com,daum.net' %}{{ email_parts.domain }}{% endif %}">
                </div>
                <input type="hidden" name="email" id="email_full" value="{{ member.email }}">
            </div>


            <!-- 연령대 -->
            <div class="mb-3 text-start">
                <label class="w-100 text-start">연령대</label><br>
                <input type="radio" name="age_group" value="10" {% if member.age_group == '10' or member.age_group == 10 %}checked{% endif %}> 10대 &nbsp;
                <input type="radio" name="age_group" value="20" {% if member.age_group == '20' or member.age_group == 20 %}checked{% endif %}> 20대 &nbsp;
                <input type="radio" name="age_group" value="30" {% if member.age_group == '30' or member.age_group == 30 %}checked{% endif %}> 30대 &nbsp;
                <input type="radio" name="age_group" value="40" {% if member.age_group == '40' or member.age_group == 40 %}checked{% endif %}> 40대 &nbsp;
                <input type="radio" name="age_group" value="50" {% if member.age_group == '50' or member.age_group == 50 %}checked{% endif %}> 50대 &nbsp;
                <input type="radio" name="age_group" value="60" {% if member.age_group == '60' or member.age_group == 60 %}checked{% endif %}> 60대 이상 &nbsp;
            </div>

            <!-- 성별 -->
            <div class="mb-3 text-start">
                <label class="w-100 text-start">성별</label><br>
                <input type="radio" name="sex" value="M" {% if member.sex == 'M' %}checked{% endif %}> 남성
                <input type="radio" name="sex" value="F" {% if member.sex == 'F' %}checked{% endif %}> 여성
            </div>

            <!-- 오류 메시지 -->
            {% if error %}
                <div class="alert alert-danger">{{ error }}</div>
            {% endif %}

            <br>
            <button type="submit" id="signupButton" class="btn btn-primary">수정하기</button>
            <br><br>

            <!-- 회원정보 수정 성공 모달 -->
            <div class="modal fade" id="signupSuccessModal" tabindex="-1" aria-labelledby="signupSuccessLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="signupSuccessLabel">회원정보수정 완료</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            수정이 완료되었습니다.
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" id="confirmButton" onclick="location.href='{% url 'member:member_page' %}'">확인</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

{% block script %}
    <script src="{% static 'js/member-edit.js' %}"></script>
{% endblock script %}

templates/member/member_page.html
{% extends 'layout/member/member_base.html' %}
{% load static %}

{% block title %}Main{% endblock title %}

{% block header %}
    {% include 'layout/member/member_header.html' %}
{% endblock header %}

{% block sidebar %}
    {% include 'layout/member/member_sidebar.html' %}
{% endblock sidebar %}

{% block content %}
    <h3 style="margin-bottom: 50px;" class="text-center">Mypage</h3>
    <div class="member-page-container">
        <!-- 프로필 정보 -->
        <div class="member-page-profile">
            <img src="{{ member.profile_image|default:'https://bucket-shim0716-250123.s3.amazonaws.com/profile_images/basic_image.jpg' }}" alt="프로필 사진">
            <p>환영합니다, {{ member.name }}님</p>
            <div class="member-page-buttons">
                <button type="button" class="btn btn-light" onclick="location.href='{% url 'member:member_edit' %}'">회원정보 수정</button>
                <button type="button" class="btn btn-light" onclick="location.href='{% url 'member:member_pw' %}'">비밀번호 변경</button>
            </div>
        </div>

        <!-- 마이페이지 정보 박스 -->
        <div class="member-page-info-boxes">
            <div class="member-page-box">포인트적립<br>({{ member.points }}p)</div>
            <div class="member-page-box">찜빵<br>{{ bread_count }}5개</div>
            <div class="member-page-box">상품문의<br>{{ inquiries }}2개</div>
            <div class="member-page-box">구매/취소내역</div>
            <div class="member-page-box">취소내역</div>
            <div class="member-page-box">전자영수증</div>
        </div>
    </div>

    <!-- 회원 탈퇴 버튼 -> 회원탈퇴 페이지로 이동 -->
    <div class="text-end">
        <button type="button" class="btn btn-danger" onclick="location.href='{% url 'member:member_delete' %}'">회원탈퇴</button>
    </div>
{% endblock content %}

templates/member/member_store.html
{% extends 'layout/store/base_store.html' %}
{% load static %}

{% block title %}회원관리{% endblock title %}

{% block header %}
    {% include 'layout/store/header_store.html' %}
{% endblock header %}

{% block sidebar %}
    {% include 'layout/store/sidebar_store.html' %}
{% endblock sidebar %}

{% block content %}
    {% load humanize %} {# intcomma 필터 사용 #}
    <h3 style="margin-bottom: 50px;" class="text-center">회원관리</h3>

    <!-- 버튼과 검색창을 한 줄에 배치 -->
    <div style="display: flex; justify-content: space-between; align-items: center;">

    <!-- 검색창 (왼쪽 정렬) -->
    <div style="flex-grow: 1; display: flex; justify-content: flex-start;">
        <form id="search-form" method="get" action="{% url 'store:member_store' %}">
            <input type="text" id="search-input" name="search" value="{{ search_query }}" placeholder="회원명을 입력하세요" style="padding: 10px; width: 250px; border: 1px solid #ccc; border-radius: 5px;">
            <button id="search_button" type="submit" name="search_button" style="background-color: lightgoldenrodyellow; padding: 10px 15px; border: none; border-radius: 5px; cursor: pointer;">검색</button>
        </form>
    </div>

    <!-- 목록 버튼 (오른쪽 정렬) -->
    <div style="flex-shrink: 0; display: flex; justify-content: flex-end;">
        <button class="btn btn-primary" type="button" onclick="location.href='{% url 'store:member_store' %}'">목록</button>
    </div>

    </div>
    <br>
    <!-- 테이블 -->
    <table class="table member-edit-table">
      <thead>
        <tr>
          <th class="checkbox-column"><input type="checkbox" id="select-all"></th>
          <th scope="col">회원명</th>
          <th scope="col">아이디</th>
          <th scope="col">연락처</th>
          <th scope="col">성별</th>
          <th scope="col">연령대</th>
          <th scope="col">이메일</th>
          <th scope="col">방문<br>횟수</th>
          <th scope="col">총 결제액<br>(원)</th>
          <th scope="col">마지막<br>방문일</th>
          <th scope="col">포인트</th>
          <th scope="col">수정</th>
          <th scope="col">
          </th>
        </tr>
      </thead>
      <tbody>
        {% for member in page_obj %}
        <tr>
            <td class="checkbox-column"><input type="checkbox" class="row-checkbox" value="{{ member.id }}"></td>
            <td>{{ member.name }}</td> <!-- 회원명 -->
            <td>{{ member.member_id }}</td> <!-- 회원아이디 -->
            <td>{{ member.phone_num}}</td> <!-- 연락처 -->
            <td>{{ member.sex}}</td> <!-- 성별 -->
            <td>{{ member.age_group}}</td> <!-- 연령대 -->
            <td>{{ member.email}}</td> <!-- 이메일 -->
            <td>{{ member.visit_count}}</td> <!-- 방문일수 -->
            <td>{{ member.total_spent|intcomma }}</td> <!-- 총 결제액(천단위에 콤마 붙이기) -->
            <td>{{ member.last_visited|date:"Y/n/j" }}</td> <!-- 마지막 방문일(년/월/일 출력) -->
            <td>{{ member.points|intcomma }}</td> <!-- 총 포인트(천단위에 콤마 붙이기) -->
            <td><button class="btn btn-warning btn-sm edit-member-btn">수정</button></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <style>
    {# 매장페이지-회원관리 수정버튼 #}
        .btn-warning {
            background-color: #ffc107 !important;
            color: #212529 !important;
            border-color: #ffc107 !important;
        }

        .btn-warning:hover {
            background-color: #e0a800 !important;
            border-color: #d39e00 !important;
        }
    </style>

    <!-- 수정용 모달 -->
    <div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="editModalLabel">회원 정보 수정</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <!-- 회원명, 연락처, 이메일 입력 폼 -->
            <div class="mb-3">
              <label for="editName" class="form-label">회원명</label>
              <input type="text" class="form-control" id="editName" required>
            </div>
            <div class="mb-3">
              <label for="editPhoneNum" class="form-label">연락처</label>
              <input type="text" class="form-control" id="editPhoneNum" required>
            </div>
            <div class="mb-3">
              <label for="editEmail" class="form-label">이메일</label>
              <input type="email" class="form-control" id="editEmail" required>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
            <button type="button" class="btn btn-primary" id="saveChangesButton">저장</button>
          </div>
        </div>
      </div>
    </div>


    <!-- 삭제와 신규등록을 한 줄에 배치 -->
    <div class="d-flex justify-content-between align-items-center mt-3" style="width: 100%;">

    <!-- 삭제 버튼 -->
    <div class="member-container" style="flex-shrink: 0;">
        <button class="btn btn-danger" type="button" id="delete-selected">삭제</button>
    </div>

    <!-- 신규등록 버튼 (오른쪽 정렬) -->
        <div style="flex-shrink: 0;">
            <button class="btn btn-success" type="button" id="new-register-btn" onclick="location.href='{% url 'main:store_signup' %}'">신규등록</button>
        </div>
    </div>

    <!-- 페이지 네비게이션 (중앙) -->
<div class="d-flex justify-content-center mt-2 mb-4">
    <nav aria-label="Page navigation">
        <ul class="pagination mb-0">
            <!-- 이전 버튼 -->
            <li class="page-ingredient {% if page_obj.has_previous %}enabled{% else %}disabled{% endif %}">
                {% if page_obj.has_previous %}
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}&search={{ search_query }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo; 이전</span>
                    </a>
                {% else %}
                    <span class="page-link" aria-label="Previous">
                        <span aria-hidden="true">&laquo; 이전</span>
                    </span>
                {% endif %}
            </li>

            <!-- 페이지 번호들 -->
            {% for page_num in page_obj.paginator.page_range %}
                {% if page_num == page_obj.number %}
                    <strong>{{ page_num }}</strong>
                {% else %}
                    <a href="?search={{ search_query }}&page={{ page_num }}">{{ page_num }}</a>
                {% endif %}
            {% endfor %}

            <!-- 다음 버튼 -->
            <li class="page-ingredient {% if page_obj.has_next %}enabled{% else %}disabled{% endif %}">
                {% if page_obj.has_next %}
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}&search={{ search_query }}" aria-label="Next">
                        <span aria-hidden="true">다음 &raquo;</span>
                    </a>
                {% else %}
                    <span class="page-link" aria-label="Next">
                        <span aria-hidden="true">다음 &raquo;</span>
                    </span>
                {% endif %}
            </li>
        </ul>
    </nav>
</div>


{% endblock content %}

{% block script %}
    <script src="{% static 'js/member_store.js' %}"></script>
{% endblock %}

templates/member/member_store_edit.html
{% extends 'layout/store/base_store.html' %}
{% load static %}

{% block title %}Store | Edit Member {% endblock %}
{% block store_id %}store_id{% endblock %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% block content %}
    
    
{% endblock content %}

{% block script %}

{% endblock script %}