breadscanso/urls.py
from django.urls import path, include
from main import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from main.views import google_login, naver_login

from django.conf import settings
from django.conf.urls.static import static


# namespace 지정
app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('summernote/', include('django_summernote.urls')),  # summernote 텍스트 에디터 추가
    path('main/', include('main.urls')), # 회원 관련 URL
    path('kiosk/', include('kiosk.urls')),  # kiosk 앱의 urls.py를 포함
    path('brand/', include('brand.urls')),  # brand 앱의 urls.py를 포함
    path('event/', include('event.urls')),  # event 앱의 urls.py를 포함
    path('member/', include('member.urls')),  # member 앱의 urls.py를 포함
    path('menu/', include('menu.urls')),  # menu 앱의 urls.py를 포함
    path('notice/', include('notice.urls')),  # notice 앱의 urls.py를 포함
    path('pay/', include('pay.urls')),  # pay 앱의 urls.py를 포함
    path('qna/', include('qna.urls')),  # qna 앱의 urls.py를 포함
    path('sales/', include('sales.urls')),  # sales 앱의 urls.py를 포함
    path('stock/', include('stock.urls')),  # stock 앱의 urls.py를 포함
    path('store/', include('store.urls')),  # store 앱의 urls.py를 포함
    path('store_info/', include('store_info.urls')),  # store_info 앱의 urls.py를 포함
    path('admin/', admin.site.urls),  # 소셜로그인 추가
    path('accounts/', include('allauth.urls')),  # 소셜로그인 추가, allauth 관련 url 추가
    path('google-login/', google_login, name='google_login'),
    path('naver-login/', naver_login, name='naver_login'),
]

# 개발 환경에서 미디어 파일 서빙
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# from django.urls import path, include
# from main import views
# from django.contrib.auth import views as auth_views
#
# # namespace 지정
# app_name = 'main'
#
# urlpatterns = [
#     path('', views.index, name='index'),
#     path('kiosk/', include('kiosk.urls')),  # kiosk 앱의 urls.py를 포함
#     path('brand/', include('brand.urls')),  # brand 앱의 urls.py를 포함
#     path('event/', include('event.urls')),  # event 앱의 urls.py를 포함
#     path('member/', include('member.urls')),  # member 앱의 urls.py를 포함
#     path('menu/', include('menu.urls')),  # menu 앱의 urls.py를 포함
#     path('notice/', include('notice.urls')),  # notice 앱의 urls.py를 포함
#     path('pay/', include('pay.urls')),  # pay 앱의 urls.py를 포함
#     path('qna/', include('qna.urls')),  # qna 앱의 urls.py를 포함
#     path('sales/', include('sales.urls')),  # sales 앱의 urls.py를 포함
#     path('stock/', include('stock.urls')),  # stock 앱의 urls.py를 포함
#     path('store/', include('store.urls')),  # store 앱의 urls.py를 포함
#     path('store_info/', include('store_info.urls')),  # store_info 앱의 urls.py를 포함
#     path("login/", auth_views.LoginView.as_view(template_name="main/login.html"), name="login"),  # 로그인 경로
#     path("logout/", auth_views.LogoutView.as_view(next_page="/"), name="logout"),  # 로그아웃 경로
#     path("signup/", views.signup, name="signup"),  # 회원가입 경로
#     path("login_find/", views.login_find, name="login_find"), # ID/PW 찾기 경로
# ]

main/urls.py
from django.urls import path, include
from main import views
from django.contrib.auth import views as auth_views

# namespace 지정
app_name = 'main'

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.user_login, name="login"),
    # path("login/", auth_views.LoginView.as_view(template_name="main/login.html"), name="login"),  # 로그인 경로
    # path("logout/", auth_views.LogoutView.as_view(next_page="/"), name="logout"),  # 로그아웃 경로
    path("logout/", views.user_logout, name="logout"),
    path("signup/", views.signup, name="signup"),  # 회원가입 경로
    path("login_find/", views.login_find, name="login_find"),  # ID/PW 찾기 경로
    path("check_user_id/", views.check_user_id, name="check_user_id"), # AJAX 요청 받는 아이디 중복 확인용
    path("sales/", include("sales.urls")), # sales 앱 URL 포함하기
    path("store_signup/", views.store_signup, name="store_signup"),  # 매장페이지-회원가입 경로
]

pay/urls.py
from django.urls import path
from . import views  # views.py에서 함수 가져오기

# namespace 지정
app_name = 'pay'

urlpatterns = [
    path('', views.pay_main, name='pay_main'),  # /pay/

    path('details/<int:payment_id>/', views.pay_details, name='pay_details'),

    path('cancel/', views.pay_cancel, name='pay_cancel'),

    path('member/', views.pay_member, name='pay_member'),

    path('member/cancel/', views.pay_member_cancel, name='pay_member_cancel'),

    path('member/details/<int:payment_id>/', views.pay_member_details, name='pay_member_details'),
    # path('member/details/<int:payment_id>/', views.pay_member_details, name='pay_member_details'),

]

sales/urls.py
from django.urls import path
from . import views
from . import chat_views

app_name= "sales"

urlpatterns = [
    path('', views.sales_main, name='sales_main'),
    path("chatbot/", chat_views.sales_chatbot, name="sales_chatbot"),
]

store/urls.py
from django.urls import path
from . import views  # views.py에서 함수 가져오기
from django.conf.urls.static import static
from django.conf import settings


app_name = 'store'

urlpatterns = [
    path('', views.store_main, name='store_main'),  # /store/
    path('member_store/', views.member_store, name='member_store'), # 매장페이지 - 회원관리
    path('update_member_store/', views.update_member_store, name='update_member_store'), # 매장페이지 - 회원관리 내 수정
    path('delete_member_store/', views.delete_member_store, name='delete_member_store'),  # 회원 삭제
    path('store_home_edit/', views.store_home_edit, name='store_home_edit'),  # 첫 번째 화면
    path('store_home_edit_details/', views.store_home_edit_details, name='store_home_edit_details'),  # 두 번째 화면
    path('about_breadscanso_edit', views.about_breadscanso_edit, name='about_breadscanso_edit'),  # 브랜드 소개
    path('store_map/', views.store_map, name='store_map'),  # 매장 안내
    path('store_map', views.store_map, name='store_map'),  # 매장 안내
    path('store_map/edit', views.store_map_edit, name='store_map_edit'),  # 매장 안내 수정
    path('store_event', views.store_event, name='store_event'),  # 이벤트 목록
    path('store_event/add', views.store_event_add, name='store_event_add'),  # 이벤트 신규등록 페이지
    path('event/<int:event_id>/edit/', views.event_edit, name='store_event_edit'),  # 수정 페이지 URL
    path('delete_store_event/', views.delete_store_event, name='delete_store_event'),  # 이벤트 삭제

    # path('community_notice', views.community_notice, name='community_notice'),  # 커뮤니티/공지사항
    # path('community_notice/write', views.community_notice_write, name='community_notice_write'),  # 커뮤니티/공지사항 글쓰기
    # path('community_notice/modify/<int:notice_id>', views.community_notice_modify, name='community_notice_modify'),  # 커뮤니티/공지사항 수정
    # path('community_qna', views.community_qna, name='community_qna'),  # 커뮤니티/Q&A

    # # question관련 view
    # path('community_qna/question/<int:qna_id>/', views.question_detail, name='question_detail'),
    # path('community_qna/question/create/', views.question_create, name='question_create'),
    # path('community_qna/question/modify/<int:qna_id>/', views.question_modify, name='question_modify'),
    # path('community_qna/question/delete/<int:qna_id>/', views.question_delete, name='question_delete'),
    #
    # # question관련 view - ajax
    # # path('community_qna/question/search/', views.question_search, name='question_search'),
    # # path('community_qna/question/vote/<int:question_id>/', views.question_vote, name='question_vote'),
    #
    # # answer관련 view
    # path('community_qna/answer/create/<int:qna_id>/',views.answer_create, name='answer_create'),
    # path('community_qna/answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    # path('community_qna/answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    #
    # # answer관련 view - ajax
    # # path('community_qna/answer/vote/<int:answer_id>/', views.answer_vote, name='answer_vote'),


    path('store_account', views.store_account, name='store_account'),  # 매장정보
]


# 개발 환경에서 미디어 파일 처리
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms


### Models ###
# class Question(models.Model):
#     # Question -> User 참조가 author, voter 두개이므로, 역참조명 related_name을 반드시 설정해서 구분해야 한다.
#     author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='questions')
#     subject = models.CharField(max_length=200)
#     content = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)
#     modified_at = models.DateTimeField(auto_now=True)
#     voter = models.ManyToManyField(User, blank=True, related_name='question_votes') # 추천인 추가
#
#
# class Answer(models.Model):
#     author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='answers')
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     content = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)
#     modified_at = models.DateTimeField(auto_now=True)
#     voter = models.ManyToManyField(User, blank=True, related_name='answer_votes') # 추천인 추가
#
#
# ### Forms ###
# class QuestionForm(forms.ModelForm):
#
#     class Meta:
#         model = Question
#         fields = ['subject', 'content'] # Form클래스에서 사용할 Model클래스 속성
#         # template에서 사용자에게 노출할 필드명
#         labels = {
#             'subject': '제목',
#             'content': '내용',
#         }

templates/layout/store/base_store.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" charset="UTF-8">
    <title>StorePage | {% block title %}{% endblock %}</title>

    <link rel="canonical" href="https://getbootstrap.kr/docs/5.3/examples/sidebars/">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://getbootstrap.kr/docs/5.3/examples/sidebars/sidebars.css">
</head>
<body>
    {% block header %}{% endblock header %}
    <hr>
    <div class="container-fluid">
        <div class="row">
            {% block sidebar %}{% endblock sidebar %}
{#            {% block content %}{% endblock content %}#}
{#            <div class="col-md-9 d-flex flex-column justify-content-center align-items-center text-center" style="min-height: 80vh;">#}
            <div class="col-md-9 d-flex flex-column justify-content-center text-center">
                {% block content %}{% endblock content %}
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script src="https://getbootstrap.kr/docs/5.3/examples/sidebars/sidebars.js"></script>
    {% block script %}{% endblock script %}
</body>
</html>

templates/layout/store/header_store.html
{% load static %}

<header class="store_header d-flex justify-content-between">
    <span id="logo">
        <a href="{% url 'index' %}"><img src="{% static 'images/brand_logo.png' %}" class="logo-img" alt="브래드스캔소 로고"></a>
    </span>
    <span class="d-flex align-items-center flex-row mb-3" style="height: 60px;  margin-right: 30px; margin-top: 30px;">
        <span class="p-2">{% if member %}{{ member.name }}{% endif %} 점장님</span>
        <form action="{% url 'main:logout' %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-light">로그아웃</button>
        </form>
    </span>

</header>

templates/layout/store/sidebar_store.html
{% load static %}

<div class="col-md-3 flex-shrink-0 p-3" style="width: 280px;">
    <a href="{% url 'sales:sales_main' %}" class="d-flex align-items-center pb-3 mb-3 link-body-emphasis text-decoration-none border-bottom">
{#      <svg class="bi pe-none me-2" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>#}
        <span class="fs-5 fw-semibold">Store</span>
    </a>
    <ul class="list-unstyled ps-0">
        <li class="mb-1">
            <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#sale_info" aria-expanded="false">
                매출정보
            </button>
            <div class="collapse" id="sale_info">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a href="{% url 'sales:sales_main' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded">그래프</a></li>
                    <li><a href="{% url 'sales:sales_chatbot' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded">AI챗봇</a></li>
                </ul>
            </div>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#inventory" aria-expanded="false">
                재고정보
            </button>
            <div class="collapse" id="inventory" style="">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a href="{% url 'stock_product' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded">제품</a></li>
                    <li><a href="{% url 'stock_ingredient' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded">재료</a></li>
                </ul>
            </div>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" aria-expanded="false" onclick="location.href='{% url 'menu_store' %}'">
                메뉴관리
            </button>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" aria-expanded="false" onclick="location.href='{% url 'pay:pay_main' %}'">
                결제관리
            </button>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" aria-expanded="false" onclick="location.href='{% url 'store:member_store' %}'">
                회원관리
            </button>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#system-collapse" aria-expanded="false">
                시스템설정
            </button>
            <div class="collapse" id="system-collapse">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li>▪️ 화면관리</li>
                    <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small ps-3">
                        <li><a href="{% url 'store:store_home_edit' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded">홈 화면 수정</a></li>
                        <li><a href="{% url 'store:about_breadscanso_edit' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded">브랜드 소개</a></li>
                        <li><a href="{% url 'store:store_map' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded">매장 안내</a></li>
                        <li><a href="{% url 'store:store_event' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded">이벤트</a></li>
                        <li><a href="{% url 'notice_store' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded">공지사항</a></li>
                    </ul>
                    <li><a href="{% url 'store:store_account' %}" class="link-body-emphasis d-inline-flex text-decoration-none rounded">⚙️매장 정보</a></li>
                </ul>
            </div>
        </li>
    </ul>
</div>